# Generated by Django 5.2.17 on 2026-08-28 12:11

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objekt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Link zum Inserat')),
                ('portal', models.CharField(blank=True, choices=[('idealista', 'idealista'), ('immoscout24', 'ImmoScout24'), ('sonstiges', 'sonstiges')], default='', max_length=20, verbose_name='Portal')),
                ('inserats_id', models.CharField(blank=True, default='', help_text='Zusammen mit dem Portal der Dublettenschlüssel. Ab Schritt 2 vom Parser gefüllt.', max_length=100, verbose_name='Inserats-ID')),
                ('titel', models.CharField(blank=True, default='', max_length=300, verbose_name='Titel des Inserats')),
                ('ort', models.CharField(blank=True, default='', max_length=150, verbose_name='Ort')),
                ('land', models.CharField(blank=True, choices=[('ES', 'Spanien'), ('DE', 'Deutschland'), ('sonstiges', 'sonstiges')], default='', max_length=20, verbose_name='Land')),
                ('region', models.CharField(blank=True, default='', help_text='Freitext. Der Suchraum ist offen und wird nicht vorab festgelegt.', max_length=150, verbose_name='Region')),
                ('objekttyp', models.CharField(blank=True, choices=[('villa', 'Villa'), ('haus', 'Haus'), ('reihenhaus', 'Reihenhaus'), ('wohnung', 'Wohnung'), ('finca', 'Finca'), ('grundstueck', 'Grundstück'), ('sonstiges', 'sonstiges')], default='', max_length=20, verbose_name='Objekttyp')),
                ('wohnflaeche', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Wohnfläche (m²)')),
                ('grundstuecksgroesse', models.DecimalField(blank=True, decimal_places=2, help_text='Bei Wohnungen leer.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Grundstücksgröße (m²)')),
                ('zimmer', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Zimmer')),
                ('baujahr', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1000)], verbose_name='Baujahr')),
                ('beschreibung', models.TextField(blank=True, default='', verbose_name='Beschreibung')),
                ('aktueller_preis', models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Redundant zum Preisverlauf - der Verlauf führt, dieses Feld hält Filter und Sortierung schnell.', max_digits=12, null=True, verbose_name='Kaufpreis (€)')),
                ('zustand', models.CharField(choices=[('kosmetisch', 'kosmetisch'), ('mittel', 'mittel'), ('kernsanierung', 'Kernsanierung'), ('unklar', 'unklar')], default='unklar', max_length=20, verbose_name='Zustand')),
                ('wert_nach_renovierung', models.DecimalField(blank=True, decimal_places=2, help_text='Grobe Schätzung. Ohne sie ist der Kaufpreis für sich aussagelos.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Wert nach Renovierung (€)')),
                ('status', models.CharField(choices=[('neu', 'neu'), ('in_pruefung', 'in Prüfung'), ('besichtigung', 'Besichtigung'), ('heisse_spur', 'heiße Spur'), ('raus', 'raus'), ('vom_markt', 'vom Markt')], default='neu', max_length=20, verbose_name='Status')),
                ('quelle', models.CharField(choices=[('url_eingeworfen', 'URL eingeworfen'), ('suchagent', 'Suchagent'), ('von_hand', 'von Hand angelegt')], default='von_hand', max_length=20, verbose_name='Quelle')),
                ('eingestellt_am', models.DateTimeField(auto_now_add=True, verbose_name='eingestellt am')),
                ('zuletzt_geaendert_am', models.DateTimeField(auto_now=True, verbose_name='zuletzt geändert am')),
                ('zuletzt_gesehen', models.DateTimeField(blank=True, help_text='Bleibt in Schritt 1 leer. Wird ab Schritt 2 beim erneuten Abruf gefüllt.', null=True, verbose_name='zuletzt gesehen')),
                ('eingestellt_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eingestellte_objekte', to=settings.AUTH_USER_MODEL, verbose_name='eingestellt von')),
                ('zuletzt_geaendert_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='geaenderte_objekte', to=settings.AUTH_USER_MODEL, verbose_name='zuletzt geändert von')),
            ],
            options={
                'verbose_name': 'Objekt',
                'verbose_name_plural': 'Objekte',
                'ordering': ['-eingestellt_am'],
            },
        ),
        migrations.CreateModel(
            name='Notiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True, verbose_name='erstellt am')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notizen', to=settings.AUTH_USER_MODEL, verbose_name='Person')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notizen', to='objekte.objekt', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Notiz',
                'verbose_name_plural': 'Notizen',
                'ordering': ['-erstellt_am', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500, verbose_name='Bild-URL')),
                ('reihenfolge', models.PositiveSmallIntegerField(default=0, verbose_name='Reihenfolge')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bilder', to='objekte.objekt', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
                'ordering': ['reihenfolge', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Preisverlauf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField(default=django.utils.timezone.localdate, verbose_name='Datum')),
                ('preis', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preis (€)')),
                ('quelle', models.CharField(choices=[('suchagenten_mail', 'Suchagenten-Mail'), ('erneuter_abruf', 'erneuter Abruf'), ('von_hand', 'von Hand')], default='von_hand', max_length=20, verbose_name='Quelle')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preise', to='objekte.objekt', verbose_name='Objekt')),
            ],
            options={
                'verbose_name': 'Preiseintrag',
                'verbose_name_plural': 'Preisverlauf',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Statusaenderung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alter_status', models.CharField(choices=[('neu', 'neu'), ('in_pruefung', 'in Prüfung'), ('besichtigung', 'Besichtigung'), ('heisse_spur', 'heiße Spur'), ('raus', 'raus'), ('vom_markt', 'vom Markt')], max_length=20, verbose_name='alter Status')),
                ('neuer_status', models.CharField(choices=[('neu', 'neu'), ('in_pruefung', 'in Prüfung'), ('besichtigung', 'Besichtigung'), ('heisse_spur', 'heiße Spur'), ('raus', 'raus'), ('vom_markt', 'vom Markt')], max_length=20, verbose_name='neuer Status')),
                ('datum', models.DateTimeField(auto_now_add=True, verbose_name='Datum')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statusaenderungen', to='objekte.objekt', verbose_name='Objekt')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='statusaenderungen', to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Statusänderung',
                'verbose_name_plural': 'Statusänderungen',
                'ordering': ['-datum', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Votum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wertung', models.CharField(choices=[('dafuer', 'dafür'), ('anschauen', 'anschauen'), ('raus', 'raus')], max_length=20, verbose_name='Wertung')),
                ('begruendung', models.TextField(blank=True, default='', verbose_name='Begründung')),
                ('geaendert_am', models.DateTimeField(auto_now=True, verbose_name='geändert am')),
                ('objekt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vota', to='objekte.objekt', verbose_name='Objekt')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vota', to=settings.AUTH_USER_MODEL, verbose_name='Person')),
            ],
            options={
                'verbose_name': 'Votum',
                'verbose_name_plural': 'Vota',
                'ordering': ['person_id'],
            },
        ),
        migrations.AddIndex(
            model_name='objekt',
            index=models.Index(fields=['status'], name='objekte_obj_status_d5a787_idx'),
        ),
        migrations.AddIndex(
            model_name='objekt',
            index=models.Index(fields=['land', 'region'], name='objekte_obj_land_265fe3_idx'),
        ),
        migrations.AddIndex(
            model_name='objekt',
            index=models.Index(fields=['aktueller_preis'], name='objekte_obj_aktuell_928090_idx'),
        ),
        migrations.AddConstraint(
            model_name='objekt',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('portal', ''), _negated=True), models.Q(('inserats_id', ''), _negated=True)), fields=('portal', 'inserats_id'), name='objekt_eindeutig_je_portal_und_inserats_id'),
        ),
        migrations.AddConstraint(
            model_name='votum',
            constraint=models.UniqueConstraint(fields=('objekt', 'person'), name='ein_votum_je_person_und_objekt'),
        ),
    ]
