# Generated by Django 5.2.17 on 2026-08-28 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objekt',
            options={'ordering': ['-eingestellt_am', '-id'], 'verbose_name': 'Objekt', 'verbose_name_plural': 'Objekte'},
        ),
    ]
