# Generated by Django 5.2.17 on 2026-09-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objekte', '0006_preisverlauf_erfasst_am'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objekt',
            name='portal',
            field=models.CharField(blank=True, choices=[('idealista', 'idealista'), ('immoscout24', 'ImmoScout24'), ('fotocasa', 'fotocasa'), ('milanuncios', 'milanuncios'), ('pisos', 'pisos'), ('immowelt', 'Immowelt'), ('sonstiges', 'sonstiges')], default='', max_length=20, verbose_name='Portal'),
        ),
    ]
